### ISSUE TITLE
Tracing is failing with Ropsten after upgrade to Besu 1.4

### ISSUE THREAD

**Issue by brianmcgee** [41north/exflo#29]
# Expected Behavior

Traces being added to postgres database and published via kafka when importing the Ropsten chain

# Current Behavior

An exception is being thrown quite early in the chain

```bash
besu_1      | java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
besu_1      |   at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
besu_1      |   at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
besu_1      |   at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
besu_1      |   at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
besu_1      |   at java.util.ArrayList.get(ArrayList.java:458) ~[?:?]
besu_1      |   at io.exflo.ingestion.tracer.ExfloOperationTracer.tracePrecompileCall(ExfloOperationTracer.kt:253) ~[plugin-e15a7da.jar:?]
besu_1      |   at org.hyperledger.besu.ethereum.mainnet.MainnetMessageCallProcessor.executePrecompile(MainnetMessageCallProcessor.java:134) ~[besu-core-1.4.4.jar:1.4.4]
besu_1      |   at org.hyperledger.besu.ethereum.mainnet.MainnetMessageCallProcessor.start(MainnetMessageCallProcessor.java:61) ~[besu-core-1.4.4.jar:1.4.4]
besu_1      |   at org.hyperledger.besu.ethereum.mainnet.AbstractMessageProcessor.process(AbstractMessageProcessor.java:167) ~[besu-core-1.4.4.jar:1.4.4]
besu_1      |   at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:361) ~[besu-core-1.4.4.jar:1.4.4]
besu_1      |   at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:306) ~[besu-core-1.4.4.jar:1.4.4]
besu_1      |   at org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:47) ~[besu-core-1.4.4.jar:1.4.4]
besu_1      |   at org.hyperledger.besu.ethereum.mainnet.TransactionProcessor.processTransaction(TransactionProcessor.java:169) ~[besu-core-1.4.4.jar:1.4.4]
besu_1      |   at io.exflo.ingestion.tracer.BlockTracer$trace$1.invoke(BlockTracer.kt:58) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.tracer.BlockTracer$trace$1.invoke(BlockTracer.kt:39) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.tracer.BlockReplay$block$1.invoke(BlockReplay.kt:57) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.tracer.BlockReplay$block$1.invoke(BlockReplay.kt:36) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.tracer.BlockReplay.performActionWithBlock(BlockReplay.kt:90) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.tracer.BlockReplay.block(BlockReplay.kt:43) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.tracer.BlockTracer.trace(BlockTracer.kt:48) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.tracker.BlockReader.trace(BlockReader.kt:125) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.postgres.tasks.TraceImportTask$run$1.apply(TraceImportTask.kt:84) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.exflo.ingestion.postgres.tasks.TraceImportTask$run$1.apply(TraceImportTask.kt:46) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:114) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnSubscriber.run(ParallelRunOn.java:273) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) ~[plugin-e15a7da.jar:?]
besu_1      |   at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56) ~[plugin-e15a7da.jar:?]
besu_1      |   at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
besu_1      |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
besu_1      |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
besu_1      |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
besu_1      |   at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Steps to Reproduce

1. Build the exflo docker image:

```bash
docker build -t 41north/exflo -f docker/exflo/Dockerfile .    
```

2. Modify `docker/exflo/docker-compose.postgres.yml`, adding the following environment variable:

```yaml
BESU_PLUGIN_EXFLO_POSTGRES_PROCESSING_LEVEL: TRACES
```

3. Run the postgres example:

```bash
docker-compose -f docker/exflo/docker-compose.postgres.yml up
```

Alternatively just apply step 2 to your intellij run config for Postgres & Ropsten.

**Comment by brianmcgee** [comment]
Besu 1.4 now implements parity style traces. I think we should remove our custom tracing and instead use the trace functionality within Besu.
